version: "3.8"

services:
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:8001 http2"
      KONG_ADMIN_LISTEN: "127.0.0.1:8001"
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000" # proxy (HTTP)
      - "8443:8443" # proxy (HTTPS)
      - "8001:8001" # admin API (local only)
    restart: unless-stopped
